name: Lerna Versioning

on:
    push:
        branches:
            - main # Trigger when pushing to main branch

jobs:
    versioning:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  npm install -g lerna
                  npm install

            - name: Configure Git identity
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Run Lerna Version
              run: |
                  npx lerna version --conventional-commits --yes  # Auto version bump based on commit messages

            - name: Push commit and tag
              run: |
                  git push origin main  # Push the version bump commit to main
                  git push origin --tags  # Push the tag created by lerna version
