name: Lerna Versioning and Publish

on:
    push:
        branches:
            - main # Trigger on push to the main branch
        tags:
            - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
    versioning-and-publishing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  registry-url: 'https://registry.npmjs.org'
                  node-version: '20'

            - name: Install dependencies
              run: |
                  npm install -g lerna
                  npm install

            - name: Configure Git identity
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Run Lerna Version
              run: |
                  npx lerna version --conventional-commits --yes  # Auto version bump based on commit messages

            - name: Publish to npm
              run: |
                  npx lerna publish from-package --yes  # Publish the updated packages to npm

              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Push commit and tag
              run: |
                  git push origin main  # Push the version bump commit to main
                  git push origin --tags  # Push the new tag created by lerna version
